name: Run Movie Recommendation Training

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.10
        environment-file: environment.yml
        activate-environment: movie-env

    - name: Run training script
      shell: cmd /C call {0}
      run: |
        python src/recommendation_system.py
