name: Run Movie Recommendation Training

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Miniconda with Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        python-version: 3.10
        environment-file: environment.yml
        activate-environment: movie-env  
        use-mamba: true  

    - name: Verify Environment and Packages
      run: |
        conda run -n movie-env python -c "import numpy, pandas, sklearn, surprise; print('All packages loaded successfully!')"

    - name: Run Training Script
      run: conda run -n movie-env python src/recommendation_system.py
