name: Run Movie Recommendation Training

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        python-version: 3.10

    - name: Create Conda Environment
      run: |
        conda env create -f environment.yml || conda env update -f environment.yml

    - name: Activate Conda Environment and Run Training
      run: |
        conda run -n movie-env python src/recommendation_system.py
