name: Run Movie Recommendation Training

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        auto-activate-base: false
        activate-environment: movie-env
        python-version: 3.10

    - name: Verify environment
      run: |
        conda info
        conda list

    - name: Run Training Script
      run: |
        conda run -n movie-env python src/recommendation_system.py
